### ISSUE TITLE
求一份预训练模型，问题

### ISSUE THREAD

**Issue by ZhidanXu** [yingqichao/retouching_FFHQ_detection#1]
请问一下，我理解的是否有问题，这个模型是可以根据美颜后的照片预测美颜程度嘛？

**Comment by yingqichao** [comment]
对的,ckpt在这里, https://drive.google.com/drive/folders/1bovqkik33bmwxtubtxlt6zljwpbogaqw?usp=sharing

readme里面也更新了

**Comment by ZhidanXu** [comment]
好的，谢谢！
